version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum  "~/code/AndroidDemo/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ~/code/AndroidDemo/gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum  "~/code/AndroidDemo/build.gradle" }}
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-16;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-16;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true
      - run:
          name: Wait emulator
          command: |
            circle-android wait-for-boot
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run EspressoTests
          command: ~/code/AndroidDemo/gradlew connectedAndroidTest
      - store_artifacts:
          path: ~/code/AndroidDemo/app/build/reports
          destination: reports
      - store_test_results:
          path: ~/code/AndroidDemo/app/build/test-results
